#!/bin/sh
#
# S98lddmodules - load/unload custom external modules
#
case "$1" in
    start)
        echo "Loading scull module..."
        /sbin/insmod /lib/modules/$(uname -r)/updates/scull.ko
        echo "Loading faulty module..."
        /sbin/insmod /lib/modules/$(uname -r)/updates/faulty.ko
        echo "Loading hello module..."
        /sbin/insmod /lib/modules/$(uname -r)/updates/hello.ko
        ;;
    stop)
        echo "Unloading scull module..."
        /sbin/rmmod scull
        echo "Unloading faulty module..."
        /sbin/rmmod faulty
        echo "Unloading hello module..."
        /sbin/rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
