#!/bin/sh

case "$1" in
	start)
		echo "Loading scull..."
		scull_load
		echo "Loading faulty..."
		module_load

		# hello load
		echo "Loading hello..."

        module="hello"
        device="hello"
        mode="664"

        # Group: since distributions do it differently, look for wheel or use staff
        # These are groups which correspond to system administrator accounts
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi

        insmod /lib/modules/"$(uname -r)"/extra/$module.ko || exit 1
        echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        if [ ! -z ${major} ]; then
            echo "Remove any existing /dev node for /dev/${device}"
            rm -f /dev/${device}
            echo "Add a node for our device at /dev/${device} using mknod"
            mknod /dev/${device} c $major 0
            echo "Change group owner to ${group}"
            chgrp $group /dev/${device}
            echo "Change access mode to ${mode}"
            chmod $mode  /dev/${device}
        else
            echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
        fi
		;;
	stop)
		echo "Unloading scull..."
		scull_unload
		echo "Unloading faulty..."
		module_unload faulty
		echo "Unloading hello..."
		rmmod hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0